# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.4.2"
darklua = "seaofvoices/darklua@0.13.1"
luau-lsp = "johnnymorganz/luau-lsp@1.32.1"
stylua = "johnnymorganz/stylua@0.20.0"
wally-package-types = "johnnymorganz/wally-package-types@1.3.2"
